/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CertificatesIndexRouteImport } from './routes/certificates/index'
import { Route as CertificatesIdIndexRouteImport } from './routes/certificates/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIdIndexRoute = CertificatesIdIndexRouteImport.update({
  id: '/certificates/$id/',
  path: '/certificates/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesIndexRoute
  '/login': typeof LoginIndexRoute
  '/certificates/$id': typeof CertificatesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesIndexRoute
  '/login': typeof LoginIndexRoute
  '/certificates/$id': typeof CertificatesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/certificates/$id/': typeof CertificatesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificates' | '/login' | '/certificates/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificates' | '/login' | '/certificates/$id'
  id: '__root__' | '/' | '/certificates/' | '/login/' | '/certificates/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  CertificatesIdIndexRoute: typeof CertificatesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$id/': {
      id: '/certificates/$id/'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof CertificatesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  CertificatesIdIndexRoute: CertificatesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
