/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/certificates': typeof CertificatesRoute
  '/login': typeof LoginRoute
  '/certificate/$id': typeof CertificateIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/certificates': typeof CertificatesRoute
  '/login': typeof LoginRoute
  '/certificate/$id': typeof CertificateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/certificates': typeof CertificatesRoute
  '/login': typeof LoginRoute
  '/certificate/$id': typeof CertificateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/certificates' | '/login' | '/certificate/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/certificates' | '/login' | '/certificate/$id'
  id: '__root__' | '/$' | '/certificates' | '/login' | '/certificate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  CertificatesRoute: typeof CertificatesRoute
  LoginRoute: typeof LoginRoute
  CertificateIdRoute: typeof CertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  CertificatesRoute: CertificatesRoute,
  LoginRoute: LoginRoute,
  CertificateIdRoute: CertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
